env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[!041420288b406dc67a48d6c0e10b68273819aaa952ccded78b7f92589334842ab11e511926084e761a516124bd540450!]
    TG_TOKEN: ENCRYPTED[!8c1141584e9006d9a8f18e1aab24d987dfc48d7715a0813120f0c1131b19b008a003fcd72baa98f4d6ab6b3c5e7c1f20!]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/fyymfgh/OrangeFox-CI/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/fyymfgh/OrangeFox-CI/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/fyymfgh/OrangeFox-CI/main/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl https://raw.githubusercontent.com/fyymfgh/OrangeFox-CI/main/scripts/upload.sh)"
